<?php

namespace App\Services;

use FPDF;

class TenantPdfService extends FPDF
{
    protected string $tenantName;

    public function __construct(string $tenantName)
    {
        parent::__construct();
        $this->tenantName = $tenantName;
    }

    // Custom Header
    function Header()
    {
        $this->SetFont('Arial', 'B', 12);
        $this->SetTextColor(50, 50, 50);
        $this->Cell(0, 10, $this->tenantName . ' - Report', 0, 1, 'C');
        $this->Ln(5);
        $this->Line(10, $this->GetY(), 200, $this->GetY());
        $this->Ln(5);
    }

    // Custom Footer
    function Footer()
    {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->SetTextColor(100, 100, 100);
        $this->Cell(0, 10, 'Page ' . $this->PageNo(), 0, 0, 'C');
        $this->Ln(5);
        $this->Cell(0, 10, 'Generated by ' . $this->tenantName, 0, 0, 'C');
    }

    // Custom content generator
    public function generateContent(array $data)
    {
        $this->AddPage();
        $this->SetFont('Arial', '', 12);

        foreach ($data as $line) {
            $this->Cell(0, 10, $line, 0, 1);
        }
    }
}
