<?php

namespace App\Http\Controllers;

use FPDF;
use Illuminate\Support\Facades\Response;

class PdfExportController extends Controller
{
    public function export()
    {
        // Use the tenant ID instead of a missing "name" field
        $tenant = tenancy()->tenant;
        $tenantId = $tenant->id ?? 'Tenant';

        // Create a new custom PDF class with header/footer
        $pdf = new class($tenantId) extends FPDF {
            protected string $tenantId;

            public function __construct($tenantId)
            {
                parent::__construct();
                $this->tenantId = $tenantId;
            }

            function Header()
            {
                $this->SetFont('Arial', 'B', 12);
                $this->Cell(0, 10, 'Tenant ID: ' . $this->tenantId . ' - Report', 0, 1, 'C');
                $this->Ln(5);
                $this->Line(10, $this->GetY(), 200, $this->GetY());
                $this->Ln(5);
            }

            function Footer()
            {
                $this->SetY(-15);
                $this->SetFont('Arial', 'I', 8);
                $this->Cell(0, 10, 'Page ' . $this->PageNo(), 0, 0, 'C');
                $this->Ln(5);
                $this->Cell(0, 10, 'Generated by Tenant ID: ' . $this->tenantId, 0, 0, 'C');
            }

            public function generateContent(array $data)
            {
                $this->AddPage();
                $this->SetFont('Arial', '', 12);

                foreach ($data as $line) {
                    $this->Cell(0, 10, $line, 0, 1);
                }
            }
        };

        $data = [
            'This is a sample line.',
            'Another line of content.',
            'One more example for your PDF.'
        ];

        $pdf->generateContent($data);

        return response($pdf->Output('S'), 200)
            ->header('Content-Type', 'application/pdf')
            ->header('Content-Disposition', 'inline; filename="tenant-report.pdf"');
    }
}
